backend/cashflow/urls.py
from django.urls import include, path

from cashflow.views import (
    CategoryCreateView, CategoryDeleteView, CategoryListView,
    CategoryUpdateView,
    RecordCreateView, RecordDeleteView, RecordListView, RecordUpdateView,
    StatusCreateView, StatusDeleteView, StatusListView, StatusUpdateView,
    SubcategoryCreateView, SubcategoryDeleteView, SubcategoryListView,
    SubcategoryUpdateView,
    TypeCreateView, TypeDeleteView, TypeListView, TypeUpdateView,
    load_categories, load_subcategories
)


app_name = 'cashflow'

record_patterns = [
    path('', RecordListView.as_view(), name='list'),
    path('create/', RecordCreateView.as_view(), name='create'),
    path('update/<int:pk>/', RecordUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', RecordDeleteView.as_view(), name='delete'),
]

status_patterns = [
    path('', StatusListView.as_view(), name='status_list'),
    path('create/', StatusCreateView.as_view(), name='status_create'),
    path('update/<int:pk>/', StatusUpdateView.as_view(), name='status_update'),
    path('delete/<int:pk>/', StatusDeleteView.as_view(), name='status_delete'),
]

type_patterns = [
    path('', TypeListView.as_view(), name='type_list'),
    path('create/', TypeCreateView.as_view(), name='type_create'),
    path('update/<int:pk>/', TypeUpdateView.as_view(), name='type_update'),
    path('delete/<int:pk>/', TypeDeleteView.as_view(), name='type_delete'),
]

category_patterns = [
    path('', CategoryListView.as_view(), name='category_list'),
    path('create/', CategoryCreateView.as_view(), name='category_create'),
    path(
        'update/<int:pk>/',
        CategoryUpdateView.as_view(), name='category_update'
    ),
    path(
        'delete/<int:pk>/',
        CategoryDeleteView.as_view(), name='category_delete'
    ),
]

subcategory_patterns = [
    path('', SubcategoryListView.as_view(), name='subcategory_list'),
    path(
        'create/', SubcategoryCreateView.as_view(), name='subcategory_create'
    ),
    path(
        'update/<int:pk>/',
        SubcategoryUpdateView.as_view(), name='subcategory_update'
    ),
    path(
        'delete/<int:pk>/',
        SubcategoryDeleteView.as_view(), name='subcategory_delete'
    ),
]

urlpatterns = [
    path('', include(record_patterns)),
    path('status/', include(status_patterns)),
    path('type/', include(type_patterns)),
    path('category/', include(category_patterns)),
    path('subcategory/', include(subcategory_patterns)),
    path(
        'ajax/load-subcategories/',
        load_subcategories, name='ajax_load_subcategories'
    ),
    path(
        'ajax/load-categories/',
        load_categories, name='ajax_load_categories'
    ),
]

backend/cashflow_project/urls.py
from django.contrib import admin
from django.urls import path, include

handler403 = 'pages.views.error_403'
handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_failure_500'

app_name = 'main'

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('cash/', include('cashflow.urls')),
]

backend/pages/urls.py
from django.urls import path

from pages.views import MainPage

app_name = 'pages'

urlpatterns = [
    path('', MainPage.as_view(), name='main'),
]

backend/templates/pages/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF токена{% endblock %}
{% block content %}
  <h1>Ошибка CSRF токена. 403</h1>
  <a href="{% url 'pages:main' %}">Вернуться на главную</a>
{% endblock %}

backend/templates/pages/main.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-header text-center">
      <h5 class="mb-0">О проекте</h5>
    </div>
    <div class="card-body">
      <p>
        <strong>CashFlowViewer</strong> — это удобный сервис для просмотра и анализа финансовых потоков.
      </p>
      <div class="d-grid gap-2 mb-3">
        <a href="{% url 'cashflow:list' %}" class="btn btn-primary">
          Финансовые операции
        </a>
      </div>

      <div class="d-flex flex-wrap gap-2 justify-content-center">
        <a href="{% url 'cashflow:status_list' %}" class="btn btn-outline-primary">
          Статусы
        </a>
        <a href="{% url 'cashflow:type_list' %}" class="btn btn-outline-primary">
          Типы
        </a>
        <a href="{% url 'cashflow:category_list' %}" class="btn btn-outline-primary">
          Категории
        </a>
        <a href="{% url 'cashflow:subcategory_list' %}" class="btn btn-outline-primary">
          Подкатегории
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}