backend/cashflow/urls.py
from django.urls import include, path

from cashflow.views import (
    CategoryCreateView, CategoryDeleteView, CategoryListView,
    CategoryUpdateView,
    RecordCreateView, RecordDeleteView, RecordListView, RecordUpdateView,
    StatusCreateView, StatusDeleteView, StatusListView, StatusUpdateView,
    SubcategoryCreateView, SubcategoryDeleteView, SubcategoryListView,
    SubcategoryUpdateView,
    TypeCreateView, TypeDeleteView, TypeListView, TypeUpdateView,
    load_categories, load_subcategories
)


app_name = 'cashflow'

record_patterns = [
    path('', RecordListView.as_view(), name='list'),
    path('create/', RecordCreateView.as_view(), name='create'),
    path('update/<int:pk>/', RecordUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', RecordDeleteView.as_view(), name='delete'),
]

status_patterns = [
    path('', StatusListView.as_view(), name='status_list'),
    path('create/', StatusCreateView.as_view(), name='status_create'),
    path('update/<int:pk>/', StatusUpdateView.as_view(), name='status_update'),
    path('delete/<int:pk>/', StatusDeleteView.as_view(), name='status_delete'),
]

type_patterns = [
    path('', TypeListView.as_view(), name='type_list'),
    path('create/', TypeCreateView.as_view(), name='type_create'),
    path('update/<int:pk>/', TypeUpdateView.as_view(), name='type_update'),
    path('delete/<int:pk>/', TypeDeleteView.as_view(), name='type_delete'),
]

category_patterns = [
    path('', CategoryListView.as_view(), name='category_list'),
    path('create/', CategoryCreateView.as_view(), name='category_create'),
    path(
        'update/<int:pk>/',
        CategoryUpdateView.as_view(), name='category_update'
    ),
    path(
        'delete/<int:pk>/',
        CategoryDeleteView.as_view(), name='category_delete'
    ),
]

subcategory_patterns = [
    path('', SubcategoryListView.as_view(), name='subcategory_list'),
    path(
        'create/', SubcategoryCreateView.as_view(), name='subcategory_create'
    ),
    path(
        'update/<int:pk>/',
        SubcategoryUpdateView.as_view(), name='subcategory_update'
    ),
    path(
        'delete/<int:pk>/',
        SubcategoryDeleteView.as_view(), name='subcategory_delete'
    ),
]

urlpatterns = [
    path('', include(record_patterns)),
    path('status/', include(status_patterns)),
    path('type/', include(type_patterns)),
    path('category/', include(category_patterns)),
    path('subcategory/', include(subcategory_patterns)),
    path(
        'ajax/load-subcategories/',
        load_subcategories, name='ajax_load_subcategories'
    ),
    path(
        'ajax/load-categories/',
        load_categories, name='ajax_load_categories'
    ),
]

backend/cashflow_project/urls.py
from django.contrib import admin
from django.urls import path, include

handler403 = 'pages.views.error_403'
handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_failure_500'

app_name = 'main'

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('cash/', include('cashflow.urls')),
]

backend/pages/urls.py
from django.urls import path

from pages.views import MainPage

app_name = 'pages'

urlpatterns = [
    path('', MainPage.as_view(), name='main'),
]

backend/cashflow/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

from cashflow_project.constants import (
    MAX_LENGTH, MAX_DIGITS, MAX_DECIMAL, LEN_CURRENCY
)

User = get_user_model()


class Status(models.Model):
    name = models.CharField(max_length=MAX_LENGTH)

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

    def __str__(self) -> str:
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=MAX_LENGTH)

    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH)
    type = models.ForeignKey(
        Type, on_delete=models.CASCADE, related_name='categories'
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=MAX_LENGTH)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='subcategories'
    )

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

    def __str__(self) -> str:
        return self.name


class CashFlowRecord(models.Model):
    date = models.DateField(
        default=timezone.now, verbose_name='Дата'
    )
    status = models.ForeignKey(
        Status, on_delete=models.PROTECT, verbose_name='Статус'
    )
    type = models.ForeignKey(
        Type, on_delete=models.PROTECT, verbose_name='Тип'
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, verbose_name='Категория'
    )
    subcategory = models.ForeignKey(
        Subcategory, on_delete=models.PROTECT, verbose_name='Подкатегория'
    )
    amount = models.DecimalField(
        max_digits=MAX_DIGITS, decimal_places=MAX_DECIMAL, verbose_name='Сумма'
    )
    currency = models.CharField(
        max_length=LEN_CURRENCY,
        choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')],
        default='RUB', verbose_name='Валюта'
    )
    comment = models.TextField(blank=True, verbose_name='Комментарий')

    class Meta:
        verbose_name = 'Запись движения средств'
        verbose_name_plural = 'Записи движения средств'

    def __str__(self) -> str:
        return self.comment[:MAX_LENGTH]

backend/cashflow/forms.py
from django import forms

from cashflow.models import CashFlowRecord, Category, Status, Subcategory, Type
from cashflow_project.constants import ROWS


class CashFlowForm(forms.ModelForm):
    date = forms.DateField(
        input_formats=['%d.%m.%Y'],
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'type': 'date'}),
        label='Дата',
        required=False
    )
    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': ROWS, 'placeholder': 'Комментарий'}
        ),
        label='Комментарий',
        required=False
    )

    class Meta:
        model = CashFlowRecord
        fields = [
            'date', 'status', 'type', 'category',
            'subcategory', 'amount', 'comment', 'currency'
        ]


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'type']
        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'Название категории'}
            ),
        }


class SubcategoryForm(forms.ModelForm):
    class Meta:
        model = Subcategory
        fields = ['name', 'category']
        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'Название подкатегории'}
            ),
            'category': forms.Select(
                attrs={'placeholder': 'Выберите категорию'}
            ),
        }


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Название статуса'})
        }


class TypeForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Название типа'})
        }

backend/cashflow/views.py
from django_filters.views import FilterView
from django.http import JsonResponse
from django.views.generic import (
    CreateView, DeleteView, ListView, UpdateView
)
from django.urls import reverse
from django.utils import timezone

from cashflow.filters import CashFlowRecordFilter
from cashflow.forms import (
    CashFlowForm, CategoryForm,
    StatusForm, SubcategoryForm, TypeForm
)
from cashflow.models import CashFlowRecord, Category, Status, Subcategory, Type
from cashflow_project.constants import PAGINATE_QUANTITY


class RecordFormMixin:
    form_class = CashFlowForm
    template_name = 'cashflow/record/form.html'

    def get_success_url(self):
        return reverse('cashflow:list')


class StatusFormMixin:
    form_class = StatusForm
    template_name = 'cashflow/status/form.html'

    def get_success_url(self):
        return reverse('cashflow:status_list')


class CategoryFormMixin:
    form_class = CategoryForm
    template_name = 'cashflow/category/form.html'

    def get_success_url(self):
        return reverse('cashflow:category_list')


class SubcategoryFormMixin:
    form_class = SubcategoryForm
    template_name = 'cashflow/subcategory/form.html'

    def get_success_url(self):
        return reverse('cashflow:subcategory_list')


class TypeFormMixin:
    form_class = TypeForm
    template_name = 'cashflow/type/form.html'

    def get_success_url(self):
        return reverse('cashflow:type_list')


class RecordListView(FilterView):
    model = CashFlowRecord
    template_name = 'cashflow/record/list.html'
    paginate_by = PAGINATE_QUANTITY
    filterset_class = CashFlowRecordFilter


class RecordCreateView(RecordFormMixin, CreateView):
    model = CashFlowRecord

    def form_valid(self, form):
        if not form.cleaned_data.get('date'):
            form.instance.date = timezone.now()
        return super().form_valid(form)


class RecordUpdateView(RecordFormMixin, UpdateView):
    model = CashFlowRecord

    def form_valid(self, form):
        if not form.cleaned_data.get('date'):
            form.instance.date = timezone.now()
        return super().form_valid(form)


class RecordDeleteView(DeleteView):
    model = CashFlowRecord
    template_name = 'cashflow/record/form.html'

    def get_success_url(self):
        return reverse('cashflow:list')


class StatusListView(ListView):
    model = Status
    paginate_by = PAGINATE_QUANTITY
    template_name = 'cashflow/status/list.html'
    ordering = ['name']


class StatusCreateView(StatusFormMixin, CreateView):
    model = Status


class StatusUpdateView(StatusFormMixin, UpdateView):
    model = Status


class StatusDeleteView(StatusFormMixin, DeleteView):
    model = Status


class CategoryListView(ListView):
    model = Category
    paginate_by = PAGINATE_QUANTITY
    template_name = 'cashflow/category/list.html'
    ordering = ['name']

    def get_queryset(self):
        qs = super().get_queryset()
        type_id = self.request.GET.get('type')
        if type_id:
            qs = qs.filter(type_id=type_id)
        return qs


class CategoryCreateView(CategoryFormMixin, CreateView):
    model = Category


class CategoryUpdateView(CategoryFormMixin, UpdateView):
    model = Category


class CategoryDeleteView(CategoryFormMixin, DeleteView):
    model = Category


class SubcategoryListView(ListView):
    model = Subcategory
    paginate_by = PAGINATE_QUANTITY
    template_name = 'cashflow/subcategory/list.html'
    ordering = ['name']

    def get_queryset(self):
        qs = super().get_queryset()
        category_id = self.request.GET.get('category')
        if category_id:
            qs = qs.filter(category_id=category_id)
        return qs


class SubcategoryCreateView(SubcategoryFormMixin, CreateView):
    model = Subcategory


class SubcategoryUpdateView(SubcategoryFormMixin, UpdateView):
    model = Subcategory


class SubcategoryDeleteView(SubcategoryFormMixin, DeleteView):
    model = Subcategory


class TypeListView(ListView):
    model = Type
    paginate_by = PAGINATE_QUANTITY
    template_name = 'cashflow/type/list.html'
    ordering = ['name']


class TypeCreateView(TypeFormMixin, CreateView):
    model = Type


class TypeUpdateView(TypeFormMixin, UpdateView):
    model = Type


class TypeDeleteView(TypeFormMixin, DeleteView):
    model = Type


def load_subcategories(request):
    category_id = request.GET.get('category')
    subcategories = Subcategory.objects.filter(
        category_id=category_id
    ).values('id', 'name')
    return JsonResponse(list(subcategories), safe=False)


def load_categories(request):
    type_id = request.GET.get('type')
    categories = Category.objects.filter(type_id=type_id).values('id', 'name')
    return JsonResponse(list(categories), safe=False)

backend/templates/cashflow/category/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование категории
  {% elif "/delete/" in request.path %}
    Удаление категории
  {% else %}
    Добавление категории
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование категории
        {% elif '/delete/' in request.path %}
          Удаление категории
        {% else %}
          Добавление категории
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              <h3>{{ object.name }}</h3>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/cashflow/category/list.html
{% extends "base.html" %}
{% block title %}
  Категории
{% endblock %}

{% block content %}
<div class="container mt-4">
  <div class="card shadow-sm">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h5 class="mb-0">Список категорий</h5>
      <a href="{% url 'cashflow:category_create' %}" class="btn btn-sm btn-primary">+ Добавить категорию</a>
    </div>
    <div class="card-body p-0">
      <div class="table-responsive">
        <table class="table table-hover table-striped mb-0 align-middle">
          <thead class="table-light">
            <tr>
              <th>Название</th>
              <th>Тип</th>
              <th>Подкатегории</th>
              <th class="text-end">Действия</th>
            </tr>
          </thead>
          <tbody>
            {% for category in page_obj %}
            <tr>
              <td>{{ category.name }}</td>
              <td>{{ category.type.name }}</td>
              <td>
                {% with subcategories=category.subcategories.all %}
                  {{ subcategories|slice:":2"|join:", " }}
                  {% if subcategories|length > 2 %}
                    …
                  {% endif %}
                  {% if subcategories %}
                    <div class="mt-1">
                      <a href="{% url 'cashflow:subcategory_list' %}?category={{ category.id }}" class="btn btn-sm btn-outline-primary">
                        Все подкатегории
                      </a>
                    </div>
                  {% else %}
                    <div class="mt-1">
                      <a href="{% url 'cashflow:subcategory_create' %}?category={{ category.id }}" class="btn btn-sm btn-outline-secondary">
                        + Добавить подкатегорию
                      </a>
                    </div>
                  {% endif %}
                {% endwith %}
              </td>
              <td class="text-end">
                <a href="{% url 'cashflow:category_update' category.pk %}" class="btn btn-sm btn-outline-warning me-1">Редактировать</a>
                <a href="{% url 'cashflow:category_delete' category.pk %}" class="btn btn-sm btn-outline-danger">Удалить</a>
              </td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="4" class="text-center text-muted py-4">
                Категории пока не добавлены.
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer">
      {% include "includes/paginator.html" %}
    </div>
  </div>
</div>
{% endblock %}